-- Drone Analytics — initial schema (PostgreSQL)
-- Uses TEXT instead of CLOB, and DOUBLE PRECISION instead of DOUBLE.

-- ── Users ─────────────────────────────────────────────────────────────────────

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)     NOT NULL,
    password_hash VARCHAR(255)     NOT NULL,
    display_name  VARCHAR(255)     NOT NULL,
    created_at    TIMESTAMP        NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- ── Flight sessions ───────────────────────────────────────────────────────────
-- report_json stores the full serialised AnalysisReportDto (including telemetry).
-- The denormalised summary columns allow fast list queries without JSON parsing.

CREATE TABLE flight_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT           NOT NULL,
    filename         VARCHAR(255)     NOT NULL,
    uploaded_at      TIMESTAMP        NOT NULL,
    report_json      TEXT             NOT NULL,
    drone_type       VARCHAR(50),
    healthy          BOOLEAN          NOT NULL DEFAULT FALSE,
    duration_seconds DOUBLE PRECISION,
    total_distance_m DOUBLE PRECISION,
    anomaly_count    INTEGER,
    risk_level       VARCHAR(50),
    CONSTRAINT fk_fs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_fs_user_uploaded ON flight_sessions (user_id, uploaded_at DESC);
