package com.droneanalytics.ingestion;

import com.droneanalytics.analytics.engine.*;
import com.droneanalytics.analytics.model.*;
import com.droneanalytics.ingestion.model.TelemetryPoint;
import org.junit.jupiter.api.*;

import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for the Step 2 analytics pipeline.
 *
 * All tests use the same 60-second circular-orbit sample flight generated by
 * SampleDataGenerator (San Francisco area, 50 m AGL peak, battery 95→80%).
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class AnalyticsTest {

    private static final Path RESOURCES = Path.of("src/test/resources");
    private static List<TelemetryPoint> points;  // shared across tests
    private static FlightSummary        summary;

    @BeforeAll
    static void setup() throws Exception {
        // Ensure sample files exist (generates them if not already present)
        SampleDataGenerator.generateAll(RESOURCES);

        // Load the ArduPilot sample — it has the richest data (AGL from BARO, voltage from BAT)
        FlightLogIngestionService ingestion = new FlightLogIngestionService();
        points = ingestion.ingest(RESOURCES.resolve("sample_ardupilot.bin"));

        // Pre-compute summary once (shared by multiple tests)
        summary = new StatisticsCalculator().calculate(points);
    }

    // -------------------------------------------------------------------------
    // 1. Statistics
    // -------------------------------------------------------------------------

    @Test @Order(1)
    void testStatistics() {
        assertNotNull(summary);

        // Duration: 59 samples at 1 Hz → ~59 seconds
        double durationSec = summary.getFlightDurationMs() / 1000.0;
        assertTrue(durationSec >= 55 && durationSec <= 65,
            "Duration should be ~59s, got " + durationSec);

        // Total distance: circular orbit + climb/descent should be > 0
        assertTrue(summary.getTotalDistanceM() > 0,
            "Total distance must be > 0");

        // Max AGL altitude: simulation peaks at 50 m
        assertTrue(summary.getMaxAltitudeAglM() >= 45 && summary.getMaxAltitudeAglM() <= 55,
            "Max AGL should be ~50 m, got " + summary.getMaxAltitudeAglM());

        // Point count
        assertEquals(points.size(), summary.getTotalPoints());

        // Sampling rate ~1 Hz
        assertTrue(summary.getSamplingRateHz() >= 0.9 && summary.getSamplingRateHz() <= 1.1,
            "Sampling rate should be ~1 Hz, got " + summary.getSamplingRateHz());
    }

    // -------------------------------------------------------------------------
    // 2. Path optimisation
    // -------------------------------------------------------------------------

    @Test @Order(2)
    void testPathOptimization() {
        PathOptimizationResult result = new PathOptimizer().analyze(points);
        assertNotNull(result);

        // The simulated flight is a circular orbit — drone returns near its start,
        // so great-circle distance ≈ 0 while actual distance >> 0.
        // Efficiency should therefore be very low (< 30%).
        assertTrue(result.getEfficiencyScore() < 30,
            "Circular orbit should have low efficiency, got " + result.getEfficiencyScore());

        // Actual distance > great-circle
        assertTrue(result.getActualDistanceM() > result.getGreatCircleDistanceM(),
            "Actual path must be longer than straight-line distance");

        // Wasted distance must be positive
        assertTrue(result.getWastedDistanceM() > 0);

        // Rating should be "Poor" for a circular orbit
        assertEquals("Poor", result.getEfficiencyRating());

        // Bearing deviations list should have entries
        assertFalse(result.getBearingDeviationsDeg().isEmpty());
    }

    // -------------------------------------------------------------------------
    // 3. Battery regression
    // -------------------------------------------------------------------------

    @Test @Order(3)
    void testBatteryRegression() {
        // Use DJI or Parrot sample for battery % data (ArduPilot only has voltage)
        List<TelemetryPoint> djiPts;
        try {
            djiPts = new FlightLogIngestionService().ingest(RESOURCES.resolve("sample_dji.txt"));
        } catch (Exception e) {
            fail("Could not load DJI sample: " + e.getMessage());
            return;
        }

        FlightSummary djiSummary = new StatisticsCalculator().calculate(djiPts);
        BatteryModel model = new BatteryRegressionEngine().fit(djiPts, djiSummary.getTotalDistanceM());
        assertNotNull(model);

        // R² should be high — linear-to-slightly-quadratic discharge is well-modelled
        assertTrue(model.getRSquared() > 0.85,
            "Battery R² should be > 0.85, got " + model.getRSquared());

        // Total drain: simulation goes 95% → 80%, so drain = 15%
        assertTrue(model.getTotalDrainPct() >= 12 && model.getTotalDrainPct() <= 18,
            "Battery drain should be ~15%, got " + model.getTotalDrainPct());

        // Average discharge rate should be positive
        assertTrue(model.getAvgDischargeRatePerMin() > 0,
            "Discharge rate must be positive");

        // Polynomial evaluate() should return a value close to observed at t=0
        double predicted0 = model.predict(0);
        assertTrue(predicted0 >= 90 && predicted0 <= 100,
            "Model should predict ~95% at t=0, got " + predicted0);

        // Coefficients array must be populated
        assertNotNull(model.getCoefficients());
        assertTrue(model.getCoefficients().length >= 2);
    }

    // -------------------------------------------------------------------------
    // 4. Anomaly detection — clean flight should have no anomalies
    // -------------------------------------------------------------------------

    @Test @Order(4)
    void testAnomalyDetectionCleanFlight() {
        List<AnomalyEvent> anomalies = new AnomalyDetector().detect(points);
        assertNotNull(anomalies);

        // The simulated flight has no injected faults, so it should be anomaly-free
        assertTrue(anomalies.isEmpty(),
            "Clean simulated flight should have 0 anomalies, got: " + anomalies);
    }

    @Test @Order(5)
    void testAnomalyDetectionTriggersOnBadData() {
        // Manually inject a GPS drift anomaly: duplicate the first point but
        // place its copy 1 degree away (≈111 km jump in 1 second)
        List<TelemetryPoint> dirty = new java.util.ArrayList<>(points);
        TelemetryPoint glitch = new TelemetryPoint();
        glitch.setTimestampMs(dirty.get(0).getTimestampMs() + 1000);
        glitch.setLatitude(dirty.get(0).getLatitude() + 1.0);   // 111 km north
        glitch.setLongitude(dirty.get(0).getLongitude());
        glitch.setAltitudeAgl(dirty.get(0).getAltitudeAgl());
        glitch.setGroundSpeed(5.0);
        glitch.setDroneType(dirty.get(0).getDroneType());
        dirty.add(1, glitch);

        List<AnomalyEvent> anomalies = new AnomalyDetector().detect(dirty);
        boolean hasGpsDrift = anomalies.stream()
            .anyMatch(a -> a.getType() == AnomalyEvent.AnomalyType.GPS_DRIFT);
        assertTrue(hasGpsDrift, "Should detect GPS_DRIFT anomaly after 111 km position jump");
    }

    // -------------------------------------------------------------------------
    // 5. Airspace risk — flight near SFO (San Francisco area)
    // -------------------------------------------------------------------------

    @Test @Order(6)
    void testAirspaceRisk() {
        // Sample flight is centred at lat=37.7749, lon=-122.4194 (San Francisco)
        // SFO airport is at lat=37.6213, lon=-122.3790 — ~17 km away
        // Our inner buffer for Class B is 9.26 km, outer 55.56 km → should score Moderate-High
        AirspaceRiskResult risk = new AirspaceRiskScorer().score(points);
        assertNotNull(risk);

        // At least one proximity event (SFO Class B is within 200 km of SF)
        assertFalse(risk.getProximityEvents().isEmpty(),
            "SF area flight should trigger at least one airspace proximity event");

        // Risk must be > 0 given proximity to SFO
        assertTrue(risk.getOverallRiskScore() > 0,
            "Risk score must be > 0 near SFO, got " + risk.getOverallRiskScore());

        // Risk level should not be null
        assertNotNull(risk.getRiskLevel());

        // Nearest zone name must be populated
        assertNotNull(risk.getNearestZoneName());
        assertFalse(risk.getNearestZoneName().isBlank());
    }

    // -------------------------------------------------------------------------
    // 6. End-to-end: AnalyticsEngine.analyze(Path) for all 5 formats
    // -------------------------------------------------------------------------

    @Test @Order(7)
    void testEndToEnd() throws Exception {
        AnalyticsEngine engine = new AnalyticsEngine();
        String[] files = {
            "sample_dji.txt",
            "sample_ardupilot.bin",
            "sample_px4.ulg",
            "sample_mavlink.tlog",
            "sample_parrot.json"
        };

        for (String file : files) {
            AnalysisReport report = engine.analyze(RESOURCES.resolve(file));

            assertNotNull(report, file + ": report must not be null");
            assertNotNull(report.getSummary(),         file + ": summary must not be null");
            assertNotNull(report.getPathOptimization(),file + ": path result must not be null");
            assertNotNull(report.getBatteryModel(),    file + ": battery model must not be null");
            assertNotNull(report.getAnomalies(),       file + ": anomalies list must not be null");
            assertNotNull(report.getAirspaceRisk(),    file + ": airspace risk must not be null");
            assertNotNull(report.getDroneType(),       file + ": drone type must not be null");

            // Status line should be non-blank
            assertFalse(report.getStatusLine().isBlank(), file + ": status line must not be blank");

            System.out.println(file + " → " + report.getStatusLine());
        }
    }
}
